name: botorch
channels:
  - pytorch
  - gpytorch
  - conda-forge
dependencies:
  - pytorch>=1.11
  - gpytorch==1.9.0
  - linear_operator==0.2.0
  - scipy
  - multipledispatch
  - pyro-ppl>=1.8.2
  - pymoo>=0.6.0
