name: rosenbrock4
benchmark: rosenbrock4
num_iters: 150
num_init: 5
parameters: null
bounds: [[-1.5, 1.5], [-1.5, 1.5], [-1.5, 1.5], [-1.5, 1.5]]
prior_location: [1, 1, 1, 1]
noise_std: 2.5
range: 11718