name: gp_4dim
benchmark: gp_4dim
num_iters: 150
num_init: 5
parameters: null
bounds: [[0, 1], [0, 1], [0, 1], [0, 1]] 
noise_std: 0.5
prior_location: [0.0, 0.0, 0.0, 0.0]
model_parameters:
  lengthscale: [0.2, 0.2, 0.2, 0.2]
  outputscale: [1]