name: rosenbrock4
benchmark: rosenbrock4
num_iters: 100
num_init: 5
parameters: null
bounds: [[-2.048, 2.048], [-2.048, 2.048], [-2.048, 2.048], [-2.048, 2.048]] 
prior_location: [1, 1, 1, 1]
noise_std: 0.1